//! `deft migrate --from=cmake`
//!
//! A deliberately naive, pattern-based parser for `CMakeLists.txt`. It
//! recognizes a handful of canonical primitives — `project`,
//! `add_executable`, `add_library`, `target_include_directories`,
//! `target_link_libraries` — and emits a starter `deft.toml`. CMake's
//! scripting constructs (`foreach`, `function`, `if`, generator expressions,
//! ...) are not interpreted; when present, deft just flags them so the user
//! knows to port that logic by hand. No CMake-parsing crate is pulled in —
//! this is plain string scanning, in keeping with deft's "no heavy deps"
//! rule.

use std::fs;
use std::path::{Path, PathBuf};

use crate::cli::MigrateArgs;
use crate::error::{DeftError, IoPathExt, Result};

/// Run `deft migrate`.
pub fn run(args: &MigrateArgs, quiet: bool) -> Result<()> {
    if args.from != "cmake" {
        return Err(DeftError::Config(format!(
            "migration from '{}' is not supported yet (only 'cmake' is implemented)",
            args.from
        )));
    }

    let root = args.path.clone().unwrap_or_else(|| PathBuf::from("."));
    let cmake_path = root.join("CMakeLists.txt");
    let text = fs::read_to_string(&cmake_path).path_ctx(&cmake_path)?;

    let project = parse_cmake(&text);

    let manifest_path = root.join("deft.toml");
    if manifest_path.exists() {
        return Err(DeftError::LayoutViolation(format!(
            "{} already exists; refusing to overwrite",
            manifest_path.display()
        )));
    }
    fs::write(&manifest_path, project.render_manifest()).path_ctx(&manifest_path)?;

    if !quiet {
        println!(
            "\x1b[1;32m   Migrated\x1b[0m {} -> {}",
            cmake_path.display(),
            manifest_path.display()
        );
        project.print_notices();
    }
    // Mixed-language fallout is always reported, even under --quiet: it lists
    // exactly what the migration could NOT map automatically, which is the
    // one thing a user re-running this non-interactively still needs to see.
    project.print_unmapped_warning();
    Ok(())
}

/// Everything the naive parser managed to extract from a CMakeLists.txt.
///
/// `deft migrate` must never abort on a mixed-language project — CMake places
/// no single-language restriction on a target, but deft does. Rather than
/// erroring out, the parser picks the dominant language by source count and
/// quarantines the minority-language files into `conflicting_sources`,
/// leaving them as explicit TODOs instead of a hard failure.
#[derive(Default)]
struct CMakeProject {
    name: Option<String>,
    is_library: bool,
    /// Dominant language: true if C "wins" the source-count majority.
    is_c: bool,
    /// Sources matching the dominant language — these go into the strict
    /// layout entry file.
    sources: Vec<String>,
    /// Sources of the *other* language, excluded from migration outright.
    conflicting_sources: Vec<String>,
    include_dirs: Vec<String>,
    link_libs: Vec<String>,
    complex_hits: Vec<String>,
}

impl CMakeProject {
    fn render_manifest(&self) -> String {
        let name = self
            .name
            .clone()
            .unwrap_or_else(|| "my_project".to_string());

        let mut out = String::new();
        out.push_str("# Generated by `deft migrate --from=cmake`.\n");
        out.push_str(
            "# Review the TODOs below — deft's CMake parser only understands a few\n\
             # canonical primitives; loops, functions, and generator expressions are\n\
             # not interpreted and must be ported by hand.\n\n",
        );

        out.push_str("[package]\n");
        out.push_str(&format!("name = \"{name}\"\n"));
        out.push_str("version = \"0.1.0\"\n\n");

        out.push_str("[features]\ndefault = []\n\n");

        let profile_key = if self.is_c { "c" } else { "cpp" };
        out.push_str(&format!("[profile.{profile_key}]\n"));
        out.push_str(if self.is_c {
            "standard = \"c17\"\n"
        } else {
            "standard = \"c++20\"\n"
        });
        out.push_str("warnings = [\"all\", \"extra\"]\n");
        out.push_str("optimization = \"0\"\n");
        if !self.include_dirs.is_empty() {
            let flags: Vec<String> = self
                .include_dirs
                .iter()
                .map(|d| format!("\"-I{d}\""))
                .collect();
            out.push_str(&format!("extra_flags = [{}]\n", flags.join(", ")));
        }
        out.push('\n');

        out.push_str("[dependencies]\n");
        if !self.link_libs.is_empty() {
            out.push_str(
                "# TODO: map these CMake target_link_libraries to deft `gh:user/lib` deps\n\
                 # (deft cannot infer a repository from a bare library name):\n",
            );
            for lib in &self.link_libs {
                out.push_str(&format!(
                    "# \"gh:<user>/{lib}\" = \"x.y.z\"  # was: {lib}\n"
                ));
            }
        }

        if !self.conflicting_sources.is_empty() {
            let dominant = if self.is_c { "C" } else { "C++" };
            let other = if self.is_c { "C++" } else { "C" };
            out.push_str("\n# TODO: Manually resolve mixed-language translation units\n");
            out.push_str(&format!(
                "# deft enforces one language per package; {dominant} was chosen as the\n\
                 # dominant language by source count. These {other} source(s) were excluded\n\
                 # from this migration and need a plan (e.g. a sibling deft package):\n"
            ));
            for s in &self.conflicting_sources {
                out.push_str(&format!("#   - {s}\n"));
            }
        }

        out
    }

    fn print_notices(&self) {
        if !self.sources.is_empty() {
            let entry = match (self.is_library, self.is_c) {
                (false, false) => "src/main.cpp",
                (false, true) => "src/main.c",
                (true, false) => "src/lib.cpp",
                (true, true) => "src/lib.c",
            };
            println!(
                "\x1b[1;33mnote\x1b[0m: deft uses a strict layout — there is no \"sources\" \
                 list in deft.toml. Move/merge these detected sources into {entry} by hand:"
            );
            for s in &self.sources {
                println!("         - {s}");
            }
        }
        if !self.complex_hits.is_empty() {
            println!(
                "\x1b[1;33mnote\x1b[0m: CMakeLists.txt uses constructs deft does not parse \
                 ({}). Review the file manually for logic not captured above.",
                self.complex_hits.join(", ")
            );
        }
    }

    /// Report — to stderr, unconditionally — exactly which detected source
    /// files could not be folded into the generated manifest because they
    /// conflict with deft's single-language rule. This is the migration
    /// tool's "never crash, always tell the user what's left" guarantee.
    fn print_unmapped_warning(&self) {
        if self.conflicting_sources.is_empty() {
            return;
        }
        let dominant = if self.is_c { "C" } else { "C++" };
        let other = if self.is_c { "C++" } else { "C" };
        eprintln!(
            "\x1b[1;33mwarning\x1b[0m: mixed-language CMake project detected — {dominant} was \
             chosen as the dominant language ({} {dominant} vs. {} {other} source file(s)). \
             The following {other} file(s) could not be mapped automatically and were left as \
             TODOs in deft.toml:",
            self.sources.len(),
            self.conflicting_sources.len()
        );
        for s in &self.conflicting_sources {
            eprintln!("           - {s}");
        }
    }
}

fn is_cpp_source(name: &str) -> bool {
    matches!(
        Path::new(name).extension().and_then(|e| e.to_str()),
        Some("cc" | "cpp" | "cxx" | "c++" | "cp")
    )
}

/// Strip `#`-style line comments. CMake's rare `#[[ ]]` bracket comments are
/// left alone — a naive tool errs on the side of flagging unfamiliar syntax
/// rather than silently mis-parsing it.
fn strip_comments(text: &str) -> String {
    text.lines()
        .map(|line| line.split('#').next().unwrap_or(""))
        .collect::<Vec<_>>()
        .join("\n")
}

fn unquote(token: &str) -> String {
    let t = token.trim();
    for q in ['"', '\''] {
        if t.len() >= 2 && t.starts_with(q) && t.ends_with(q) {
            return t[1..t.len() - 1].to_string();
        }
    }
    t.to_string()
}

/// Find every invocation of `command(...)` and return the raw argument text
/// inside the parens. A depth-counted scan handles nested parens (CMake
/// `if()` conditions sometimes nest); it does not understand parens inside
/// quoted strings, an accepted limitation for a "naive" migration tool.
fn extract_calls(text: &str, command: &str) -> Vec<String> {
    let mut calls = Vec::new();
    let bytes = text.as_bytes();
    let needle = format!("{command}(");
    let lower_text = text.to_ascii_lowercase();
    let lower_needle = needle.to_ascii_lowercase();

    let mut search_from = 0;
    while search_from < lower_text.len() {
        let Some(rel) = lower_text[search_from..].find(&lower_needle) else {
            break;
        };
        let start = search_from + rel + needle.len();
        let mut depth = 1usize;
        let mut end = start;
        while end < bytes.len() && depth > 0 {
            match bytes[end] {
                b'(' => depth += 1,
                b')' => depth -= 1,
                _ => {}
            }
            end += 1;
        }
        if depth == 0 {
            calls.push(text[start..end - 1].to_string());
        }
        search_from = end.max(start + 1);
    }
    calls
}

fn parse_cmake(raw: &str) -> CMakeProject {
    let text = strip_comments(raw);
    let mut project = CMakeProject::default();

    if let Some(call) = extract_calls(&text, "project").into_iter().next() {
        let name = call.split_whitespace().next().map(unquote);
        if let Some(name) = name.filter(|n| !n.is_empty()) {
            project.name = Some(name);
        }
    }

    for call in extract_calls(&text, "add_executable") {
        let mut tokens = call.split_whitespace();
        let target = tokens.next().map(unquote);
        if project.name.is_none() {
            project.name = target;
        }
        project.sources.extend(tokens.map(unquote));
        project.is_library = false;
    }

    for call in extract_calls(&text, "add_library") {
        let mut tokens = call.split_whitespace();
        let target = tokens.next().map(unquote);
        if project.name.is_none() {
            project.name = target;
        }
        for tok in tokens {
            if matches!(tok, "STATIC" | "SHARED" | "MODULE" | "INTERFACE" | "OBJECT") {
                continue;
            }
            project.sources.push(unquote(tok));
        }
        project.is_library = true;
    }

    for call in extract_calls(&text, "target_include_directories") {
        let mut tokens = call.split_whitespace();
        tokens.next(); // target name — deft has one implicit target per package
        for tok in tokens {
            if matches!(tok, "PUBLIC" | "PRIVATE" | "INTERFACE") {
                continue;
            }
            project.include_dirs.push(unquote(tok));
        }
    }

    for call in extract_calls(&text, "target_link_libraries") {
        let mut tokens = call.split_whitespace();
        tokens.next(); // target name
        for tok in tokens {
            if matches!(tok, "PUBLIC" | "PRIVATE" | "INTERFACE") {
                continue;
            }
            project.link_libs.push(unquote(tok));
        }
    }

    project.include_dirs.sort();
    project.include_dirs.dedup();
    project.link_libs.sort();
    project.link_libs.dedup();

    // Pick the dominant language by source count rather than erroring out on
    // a mix — CMake permits mixed-language targets even though deft doesn't.
    // Ties favor C++, matching `deft init`'s own default.
    let cpp_count = project.sources.iter().filter(|s| is_cpp_source(s)).count();
    let c_count = project.sources.len() - cpp_count;
    project.is_c = c_count > cpp_count;

    let dominant_is_cpp = !project.is_c;
    let all_sources = std::mem::take(&mut project.sources);
    let (dominant, conflicting): (Vec<String>, Vec<String>) = all_sources
        .into_iter()
        .partition(|s| is_cpp_source(s) == dominant_is_cpp);
    project.sources = dominant;
    project.conflicting_sources = conflicting;

    let lower = text.to_ascii_lowercase();
    for keyword in [
        "foreach(",
        "function(",
        "macro(",
        "while(",
        "generate_export_header(",
    ] {
        if lower.contains(keyword) {
            project
                .complex_hits
                .push(keyword.trim_end_matches('(').to_string());
        }
    }

    project
}

#[cfg(test)]
mod tests {
    use super::*;

    /// A mock mixed-language `add_executable` call: 3 C++ sources vs. 2 C
    /// sources. C++ must win the majority, the 2 C files must be quarantined
    /// into `conflicting_sources`, and parsing must complete without
    /// panicking.
    const MIXED_LANGUAGE_CMAKE: &str = r#"
        project(widgets)
        add_executable(widgets main.cpp foo.c bar.cpp baz.c qux.cpp)
        target_include_directories(widgets PUBLIC include)
        target_link_libraries(widgets pthread)
    "#;

    #[test]
    fn dominant_language_picked_by_majority_source_count() {
        let project = parse_cmake(MIXED_LANGUAGE_CMAKE);

        // 3 C++ vs. 2 C: C++ is dominant, so `is_c` must be false.
        assert!(!project.is_c);
        assert_eq!(project.sources.len(), 3);
        assert_eq!(project.conflicting_sources.len(), 2);

        for s in &project.sources {
            assert!(is_cpp_source(s), "expected dominant cpp source, got {s}");
        }
        for s in &project.conflicting_sources {
            assert!(!is_cpp_source(s), "expected minority c source, got {s}");
        }
    }

    #[test]
    fn minority_sources_become_a_todo_comment_block() {
        let project = parse_cmake(MIXED_LANGUAGE_CMAKE);
        let manifest = project.render_manifest();

        assert!(manifest.contains("# TODO: Manually resolve mixed-language translation units"));
        for s in &project.conflicting_sources {
            assert!(
                manifest.contains(&format!("#   - {s}")),
                "manifest missing TODO line for {s}:\n{manifest}"
            );
        }
        // The dominant profile (C++) must be the one actually emitted.
        assert!(manifest.contains("[profile.cpp]"));
        assert!(!manifest.contains("[profile.c]"));
    }

    #[test]
    fn single_language_project_has_no_conflicting_sources() {
        let text = r#"
            project(tool)
            add_executable(tool main.c util.c)
        "#;
        let project = parse_cmake(text);

        assert!(project.is_c);
        assert_eq!(project.sources.len(), 2);
        assert!(project.conflicting_sources.is_empty());

        let manifest = project.render_manifest();
        assert!(!manifest.contains("# TODO: Manually resolve mixed-language translation units"));
    }

    /// Reporting helpers must never panic, mixed-language or not — this is
    /// the migration tool's "never crash, always tell the user" guarantee.
    #[test]
    fn reporting_helpers_do_not_panic_on_mixed_or_clean_input() {
        let mixed = parse_cmake(MIXED_LANGUAGE_CMAKE);
        mixed.print_notices();
        mixed.print_unmapped_warning();
        let _ = mixed.render_manifest();

        let clean = parse_cmake("project(empty)");
        clean.print_notices();
        clean.print_unmapped_warning();
        let _ = clean.render_manifest();
    }
}
